name: Build Typst resume

on:
  push:
    paths:
      - '**.typ'
      - '.github/workflows/build-resume.yml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Compile resume with Typst
        uses: lvignoli/typst-action@main
        with:
          source_file: resume/resume.typ
          options: |
            --font-path
            fonts

      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: resume.pdf
          path: ./resume/resume.pdf

      - name: Download PDF file in website directory
        uses: actions/download-artifact@v4
        with:
          name: resume.pdf
          path: ./public

      - name: Set current date as env variable
        run: echo "NOW=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4.15.4
        with:
          file_pattern: '*.pdf'
          commit_message: 'Resume updated on ${{ env.NOW }}'
